functions used:

*NumPy*:
- np.array
- np.zeros
- np.ones
- np.random.rand

In [29]:
import numpy as np
import pandas as pd
from scipy.io  import loadmat

#### Matrix Algebra

In [10]:
# using numpy to create an array
x = np.array([[1, 2, 3], [4, 5, 6]])

# another option is to create matrices using the following functions:
zeros = np.zeros((2,3)) # matrix of zeros
ones = np.ones((2,3)) # matrix of ones
identity = np.eye(3) # identity. matrix
rand = np.random.rand(2,3) # random nums between 0 nd 1

x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
3*x

array([[ 3,  6,  9],
       [12, 15, 18]])

In [12]:
3 * x/2

array([[1.5, 3. , 4.5],
       [6. , 7.5, 9. ]])

##### Matrix addition and subtraction

In [15]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[6,5],[4,3],[2,1]])

x, y

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[6, 5],
        [4, 3],
        [2, 1]]))

In [16]:
x + y

array([[7, 7],
       [7, 7],
       [7, 7]])

In [17]:
x - y

array([[-5, -3],
       [-1,  1],
       [ 3,  5]])

##### Matrix Multiplication

- `@` symbol is for matrix multiplication (or `np.dot`)
- `*` symbol is for element wise multiplication
- `.T` is the transpose of a matrix

In [ ]:
# (3x2) @ (2x3) = (3x3)
x @ y.T


array([[28, 19],
       [40, 28]])

In [24]:
# (2x3) @ (3x2) = (2x2)
x.T @ y

array([[28, 19],
       [40, 28]])

#### For loops
a for loop repeats statements. at each iteration the for loop index (j) increases

#### A for loop repeats statements between "for" and "end".  At each iteration, the for loop index (j) increases.

In [26]:
for j in np.arange(10):
    j = j * 2
    print(j)
    

0
2
4
6
8
10
12
14
16
18


Also works for lists

In [33]:
data = loadmat('data/SIO_TEMP_1917_2025_py.mat', squeeze_me=True)

temps = data['T'][:10]
temps

array([11.5       , 11.5       , 11.9       , 11.5       , 11.7       ,
       11.9       , 12.03333333, 12.16666667, 12.3       , 12.2       ])

#### Form a 2-dimensional array of T summer day vs year using a for loop   
